disabled_rules: # 执行时排除掉的规则
  - identifier_name    # 命名规则必须按照驼峰原则，与后台传的Json字段命名冲突，建议排除掉
  - trailing_whitespace   # 每一个空行不能有空格，会与Xcode换行后自动对齐生成的空格冲突，建议排除掉
  - force_cast
#force_cast: warning # 类型判断
#force_try: warning # try语句判断

cyclomatic_complexity: 20 #代码复杂度,默认为10

excluded:   # 不检索的路径， swiftlint会无视该路径下的文件
  - Pods
  - Carthage
  
included: # 你所希望Lint检索的路径，SwiftLint会扫描该路径下的所有.swift后缀的文件


line_length:  # 单行代码长度,默认error 120
  warning: 200
  error: 300

function_body_length: # 函数体长度
  warning: 200
  error: 300
